version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - CONNECTION_URL=mongodb://mongo:27017/todoapp
      - PORT=5001
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - todo-network

  mongo:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge